### ISSUE TITLE
Microsoft Defender flags ArknightsMaterials.exe as trojan

### ISSUE THREAD

**Issue by MusicOnline** [Diceycle/Arknights-Material-Planner#1]
# Issue
Microsoft Defender (at least on Windows 11) flags ArknightsMaterials.exe as Trojan:Win32/Wacatac.B!ml and immediately quarantines it on zip extraction.
![image](https://user-images.githubusercontent.com/39178127/227752055-f966f58a-a5ec-4de9-9e05-a59876113b99.png)

# Proposed Solution
I'm aware digital signing the .exe costs money, but the README should include instructions and an explanation so that people don't get surprised when the .exe goes missing. This is especially true when release builds are not done through GitHub Actions so it's hard to determine whether this is a normal or infected release build upload.

**Comment by Diceycle** [comment]
I have added a GitHub Action workflow and added a small note in the README but beyond that there is not much I can do. Anti-Virus software flagging stuff as false-positives is so common I see that warning on pretty much any software that isn't signed by the company that made it at which point the warning is redundant anyway. 

In fact, there is no guarantee that I don't replace the EXEs after the Workflow has added them to the release, so you will always have to trust that there was no malicious action taken.

**Comment by MusicOnline** [comment]
A note in the README is sufficient for this case. Thanks!

Edit: Interestingly, it didn't get flagged when using v1.0.2.
