### ISSUE TITLE
There are no Enemies

### ISSUE THREAD

**Issue by Funlimit1** [Diceycle/Arknights-Material-Planner#2]
There is a little suggestion, what if you add an enemy, what is their status and what are their weaknesses. just that.

**Comment by Diceycle** [comment]
I'm sorry, but I won't be adding that feature. It is pretty far removed from the purpose of this tool, which is to track material costs of operator upgrades. 

Enemy stats are also not consistent and can change from stage to stage so while [Gamepress has a list of most enemies and their stats](https://ak.gamepress.gg/database/enemy-list) I recommend taking a look at [PRTS](https://map.ark-nights.com/areas) to learn about the stats of any particular enemy in a specific stage.
